---

  - name: create vpc
    ec2_vpc_net: 
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ aws_region }}"
      tags:
        name: "{{ vpc_name }}"
    register: osaka_vpc   

       
